require('dotenv').config();
const express = require('express');
const twilio = require('twilio');
const { OpenAI } = require('openai');
const axios = require('axios');
const cors = require('cors');

const app = express();
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(cors());

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
const twilioClient = twilio(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN);

// Store active calls
const activeCalls = {};
const callHistory = [];

// Incoming call handler
app.post('/incoming-call', (req, res) => {
  const callSid = req.body.CallSid;
    const callerNumber = req.body.From;

        console.log(`Incoming call from ${callerNumber}, SID: ${callSid}`);

            activeCalls[callSid] = {
                sid: callSid,
                    caller: callerNumber,
                        startTime: new Date(),
                            recordingUrl: null,
                                transcript: null,
                                    analysis: null
                                      };

                                        const twiml = new twilio.twiml.VoiceResponse();
                                          twiml.say({ language: 'he-IL', voice: 'Polly.Ayelet' }, 'שלום, הגעתם לשירות איטום והדברה. אנא המתינו להתחברות.');

                                              const dial = twiml.dial({
                                                  record: 'record-from-ringing',
                                                      recordingStatusCallback: `${process.env.SERVER_URL || 'https://server-production-eca3.up.railway.app'}/recording-complete`,
                                                          recordingStatusCallbackMethod: 'POST',
                                                              action: `${process.env.SERVER_URL || 'https://server-production-eca3.up.railway.app'}/call-complete`,
                                                                  timeout: 30
                                                                    });
                                                                      dial.number(process.env.AGENT_PHONE_NUMBER || process.env.OWNER_WHATSAPP);

                                                                        res.type('text/xml');
                                                                          res.send(twiml.toString());
                                                                          });

                                                                          // Recording complete handler
                                                                          app.post('/recording-complete', async (req, res) => {
                                                                            const callSid = req.body.CallSid;
                                                                              const recordingUrl = req.body.RecordingUrl;

                                                                                  console.log(`Recording complete for ${callSid}: ${recordingUrl}`);

                                                                                      if (activeCalls[callSid]) {
                                                                                          activeCalls[callSid].recordingUrl = recordingUrl;
                                                                                            }

                                                                                              try {
                                                                                                  // Download recording and transcribe
                                                                                                      const recordingResponse = await axios.get(`${recordingUrl}.mp3`, {
                                                                                                            auth: {
                                                                                                                    username: process.env.TWILIO_ACCOUNT_SID,
                                                                                                                            password: process.env.TWILIO_AUTH_TOKEN
                                                                                                                                  },
                                                                                                                                        responseType: 'arraybuffer'
                                                                                                                                            });
                                                                                                                                            
                                                                                                                                                const audioBuffer = Buffer.from(recordingResponse.data);
                                                                                                                                                    const { Readable } = require('stream');
                                                                                                                                                        const stream = Readable.from(audioBuffer);
                                                                                                                                                            stream.path = 'recording.mp3';
                                                                                                                                                            
                                                                                                                                                                const transcription = await openai.audio.transcriptions.create({
                                                                                                                                                                      file: stream,
                                                                                                                                                                            model: 'whisper-1',
                                                                                                                                                                                  language: 'he',
                                                                                                                                                                                        response_format: 'text'
                                                                                                                                                                                            });
                                                                                                                                                                                            
                                                                                                                                                                                                console.log(`Transcript: ${transcription}`);
                                                                                                                                                                                                
                                                                                                                                                                                                    // Analyze with GPT
                                                                                                                                                                                                        const analysis = await openai.chat.completions.create({
                                                                                                                                                                                                              model: 'gpt-4o-mini',
                                                                                                                                                                                                                    messages: [{
                                                                                                                                                                                                                            role: 'system',
                                                                                                                                                                                                                                    content: `אתה עוזר לעסק של איטום והדברה. נתח את השיחה הבאה וחלץ את הפרטים הבאים בפורמט JSON:
                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                      "customerName": "שם הלקוח אם נזכר",
                                                                                                                                                                                                                                                                "customerPhone": "מספר טלפון אם נזכר",
                                                                                                                                                                                                                                                                          "address": "כתובת אם נזכרה",
                                                                                                                                                                                                                                                                                    "problemType": "סוג הבעיה (ניתקנים/עכברים/איטום/ג'וקים/אחר)",
                                                                                                                                                                                                                                                                                              "agreedPrice": "מחיר שסוכם אם נזכר",
                                                                                                                                                                                                                                                                                                        "visitDate": "תאריך ביקור אם נזכר",
                                                                                                                                                                                                                                                                                                                  "summary": "תקציר קצר של השיחה",
                                                                                                                                                                                                                                                                                                                            "followUp": "האם יש צורך במעקב (כן/לא)"
                                                                                                                                                                                                                                                                                                                                    }`
                                                                                                                                                                                                                                                                                                                                          }, {
                                                                                                                                                                                                                                                                                                                                                  role: 'user',
                                                                                                                                                                                                                                                                                                                                                          content: transcription
                                                                                                                                                                                                                                                                                                                                                                }],
                                                                                                                                                                                                                                                                                                                                                                      response_format: { type: 'json_object' }
                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                              const analysisData = JSON.parse(analysis.choices[0].message.content);
                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                      if (activeCalls[callSid]) {
                                                                                                                                                                                                                                                                                                                                                                                            activeCalls[callSid].transcript = transcription;
                                                                                                                                                                                                                                                                                                                                                                                                  activeCalls[callSid].analysis = analysisData;
                                                                                                                                                                                                                                                                                                                                                                                                        activeCalls[callSid].endTime = new Date();
                                                                                                                                                                                                                                                                                                                                                                                                              callHistory.unshift(activeCalls[callSid]);
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                      // Send WhatsApp notification
                                                                                                                                                                                                                                                                                                                                                                                                                          await sendWhatsAppNotification(activeCalls[callSid]);
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('Error processing recording:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                    res.sendStatus(200);
                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                    // Call complete handler
                                                                                                                                                                                                                                                                                                                                                                                                                                    app.post('/call-complete', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                      const callSid = req.body.CallSid;
                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log(`Call complete: ${callSid}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                            const twiml = new twilio.twiml.VoiceResponse();
                                                                                                                                                                                                                                                                                                                                                                                                                                              res.type('text/xml');
                                                                                                                                                                                                                                                                                                                                                                                                                                                res.send(twiml.toString());
                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                // Send WhatsApp notification
                                                                                                                                                                                                                                                                                                                                                                                                                                                async function sendWhatsAppNotification(callData) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      const a = callData.analysis || {};
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const duration = callData.endTime ? 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                Math.round((new Date(callData.endTime) - new Date(callData.startTime)) / 60000) : 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const message = `📞 *שיחה חדשה - איטום והדברה*\n\n` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `🕐 ${new Date(callData.startTime).toLocaleString('he-IL')}\n` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `📱 מתקשר: ${callData.caller}\n` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      `⏱️ משך: ${duration} דקות\n\n` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `👤 לקוח: ${a.customerName || 'לא זוהה'}\n` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  `🏠 כתובת: ${a.address || 'לא נמסרה'}\n` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `🐛 בעיה: ${a.problemType || 'לא זוהה'}\n` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              `💰 מחיר: ${a.agreedPrice || 'לא סוכם'}\n` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    `📅 ביקור: ${a.visitDate || 'לא נקבע'}\n\n` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `📋 תקציר: ${a.summary || 'אין'}\n` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `🔔 מעקב: ${a.followUp || 'לא'}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await twilioClient.messages.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          from: `whatsapp:${process.env.TWILIO_PHONE_NUMBER}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                to: `whatsapp:${process.env.OWNER_WHATSAPP}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      body: message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log('WhatsApp notification sent');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error('Error sending WhatsApp:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // API - Get all calls
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      app.get('/api/calls', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.json(callHistory);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // API - Get single call
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.get('/api/calls/:sid', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const call = callHistory.find(c => c.sid === req.params.sid);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (call) res.json(call);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              else res.status(404).json({ error: 'Not found' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Health check
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              app.get('/', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.json({ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status: 'ok', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message: 'CallApp Server Running',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            calls: callHistory.length
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const PORT = process.env.PORT || 3000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`CallApp server running on port ${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
